on: [push, pull_request]
jobs:
  trigger-downstream-build:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke downstream workflow
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        workflow_file_name: github-actions.yml
        repo: fenghao-chen/hellosign-php-sdk
        token: ${{ secrets.PERSONAL_TOKEN }}
        ref: openapi
