on: [push, pull_request]
jobs:
  trigger-downstream-build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Invoke downstream workflow
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: fenghao-chen
        repo: hellosign-php-sdk
        workflow_file_name: github-actions.yml
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        ref: openapi
        client_payload: "{'branch_name': 'oas-release'}"
