on: [push, pull_request]
jobs:
  trigger-downstream-build:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Invoke downstream workflow
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: fenghao-chen
        repo: hellosign-php-sdk
        workflow_file_name: github-actions.yml
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        ref: openapi
