on: [push]
jobs:
  trigger-php-sdk-build:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke downstream workflow
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: fenghao-chen
        repo: hellosign-php-sdk
        workflow_file_name: github-actions.yml
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        ref: openapi
        client_payload: '{"branch_name": "${{ github.ref_name }}"}'

  trigger-python-sdk-build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke downstream workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: fenghao-chen
          repo: hellosign-python-sdk
          workflow_file_name: github-actions.yml
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          ref: openapi
          client_payload: '{"branch_name": "${{ github.ref_name }}"}'

  trigger-ruby-sdk-build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke downstream workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: fenghao-chen
          repo: hellosign-ruby-sdk
          workflow_file_name: github-actions.yml
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          ref: openapi
          client_payload: '{"branch_name": "${{ github.ref_name }}"}'

  trigger-nodejs-sdk-build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke downstream workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: fenghao-chen
          repo: hellosign-nodejs-sdk
          workflow_file_name: github-actions.yml
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          ref: openapi
          client_payload: '{"branch_name": "${{ github.ref_name }}"}'